import {INote} from "../interfaces";

export const data: INote[] = [
    {
        id: 1,
        name: "Shopping list",
        created: "April 20, 2021",
        category: "Task",
        content: "Tomatoes bread",
        dates: [],
    },
    {
        id: 2,
        name: "The theory of evolution",
        created: "April 27, 2021",
        category: "Random Thought",
        content: "The evolution",
        dates: [],
    },
    {
        id: 3,
        name: "New Feature",
        created: "May 05, 2021",
        category: "Idea",
        content: "Implement new ...",
        dates: ["3/5/2021", "5/5/2021"],
    },
    {
        id: 4,
        name: "William Gaddis",
        created: "May 07, 2021",
        category: "Quote",
        content: "Power doesn't corrupt people; people corrupt power.",
        dates: [],
    },
    {
        id: 5,
        name: "Books",
        created: "May 15, 2021",
        category: "Task",
        content: "The lean startup",
        dates: [],
    },
    {
        id: 6,
        name: "Marcus Tullius Cicero",
        created: "December 31, 2021",
        category: "Quote",
        content: "A room without books is like a body without a soul",
        dates: [],
    },
    {
        id: 7,
        name: "Mae West",
        created: "January 1, 2022",
        category: "Quote",
        content: "You only live once, but if you do it right, once is enough",
        dates: [],
    },
];